# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(recipes)
    library(workflows)
    library(xgboost)
}


b <- board_folder(path = "/media/hd1/canadasreche@gmail.com/Jornadas_barcelona_2023/road-to-production/Taller/modelos/modelo_vetiver")
v <- vetiver_pin_read(b, "mod_vetiver_valve", version = "20231112T080220Z-0f297")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
