
FROM joscani/rprodbarcelona2023

COPY logistic_model.rds plumber_async_ejercicio.R launch.R ./

RUN  mkdir /opt/ml \
     && mv logistic_model.rds /opt/ml/logistic_model.rds \
     && mv  plumber_async_ejercicio.R /opt/ml/plumber.R

EXPOSE 8000
CMD R -e "source('launch.R')"

