# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(kknn)
    library(parsnip)
    library(recipes)
    library(workflows)
}
b <- board_folder(path = "/media/hd1/canadasreche@gmail.com/Jornadas_barcelona_2023/road-to-production/Taller/modelos/modelo_vetiver")
v <- vetiver_pin_read(b, "vetiver_iris", version = "20231029T182655Z-ae7c8")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
