
FROM joscani/rprodbarcelona2023

COPY brms_model.rds plumber_async.R launch.R ./

RUN  mkdir /opt/ml \
     && mv brms_model.rds /opt/ml/brms_model.rds \
     && mv plumber_async.R /opt/ml/plumber.R 

EXPOSE 8000
CMD R -e "source('launch.R')"

